### PR TITLE
copyrighter_patch

### PR DESCRIPTION
**Pull request by TwitRco**
[artist-copyright - nl (1).pdf](https://github.com/firebase/quickstart-unity/files/1641513/artist-copyright.-.nl.1.pdf)

### CODE REVIEW

**Comment by TwitRco** [comment]
quickstart-unity/CONTRIBUTING.md

**Comment by stewartmiles** [comment]
@TwitRco I don't follow what you're trying to do in this patch.  Could you:
- Squash (rebase) all commits into a single patch
- Update the commit description with the details of what you're trying to achieve here?

Cheers,
Stewart

**Comment by avidesa1** [comment]
Sweet tooth satisfaction

**Comment by TwitRco** [comment]
#goudblond to get satisfactie

**Pull request closed without merging**
